AWSTemplateFormatVersion: '2010-09-09'
Description: "App infra: Glue jobs, Lambdas, EventBridge automation"

Parameters:
  ArtifactsBucketName:
    Type: String
  DatalakeBucketName:
    Type: String
  GlueServiceRoleName:
    Type: String
  LambdaExecutionRoleArn:
    Type: String

Resources:

  RequestsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: sylvester-requests-layer
      Description: "Python requests library for ingestion Lambda"
      Content:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: lambda/layers/requests_layer.zip
      CompatibleRuntimes:
        - python3.12

  GlueJobBronzeToSilver:
    Type: AWS::Glue::Job
    Properties:
      Name: sylvester_bronze_to_silver
      Role: !Ref GlueServiceRoleName
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${ArtifactsBucketName}/glue/sylvester_bronze_to_silver.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      DefaultArguments:
        --job-language: "python"
        --enable-continuous-cloudwatch-log: "true"
        --enable-metrics: "true"
        --BRONZE_BUCKET: !Sub "${DatalakeBucketName}/bronze/"
        --SILVER_BUCKET: !Sub "${DatalakeBucketName}/silver/"
      MaxRetries: 0

  GlueJobSilverToGold:
    Type: AWS::Glue::Job
    Properties:
      Name: sylvester_silver_to_gold
      Role: !Ref GlueServiceRoleName
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${ArtifactsBucketName}/glue/sylvester_silver_to_gold.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      DefaultArguments:
        --job-language: "python"
        --enable-continuous-cloudwatch-log: "true"
        --enable-metrics: "true"
        --SILVER_BUCKET: !Sub "${DatalakeBucketName}/silver/"
        --GOLD_BUCKET: !Sub "${DatalakeBucketName}/gold/"
      MaxRetries: 0

  IngestionLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: sylvester_ingestion_lambda
      Role: !Ref LambdaExecutionRoleArn
      Runtime: python3.12
      Handler: sylvester_ingestion.lambda_handler
      Code:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: lambda/sylvester_ingestion.zip
      Timeout: 120
      Environment:
        Variables:
          DATALAKE_BUCKET: !Ref DatalakeBucketName
          BRONZE_PREFIX: bronze/
          BRONZE_TO_SILVER_JOB: sylvester_bronze_to_silver
          API_URL: "https://www.vaikcam.com/api/loans/"
          API_KEY: "sylvester-api-secrete-key-003£&"   # ideally, use AWS Secrets Manager or Parameter Store for better security
      Layers:
        - !Ref RequestsLayer

  TriggerSilverToGoldLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: sylvester_trigger_silver_to_gold
      Role: !Ref LambdaExecutionRoleArn
      Runtime: python3.12
      Handler: sylvester_trigger_silver_to_gold.lambda_handler
      Code:
        S3Bucket: !Ref ArtifactsBucketName
        S3Key: lambda/sylvester_trigger_silver_to_gold.zip
      Timeout: 60
      Environment:
        Variables:
          SILVER_TO_GOLD_JOB: sylvester_silver_to_gold

  BronzeToSilverSucceededRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger when Sylvester Bronze-to-Silver Glue job succeeds
      EventPattern:
        source: ["aws.glue"]
        detail-type: ["Glue Job State Change"]
        detail:
          jobName: ["sylvester_bronze_to_silver"]
          state: ["SUCCEEDED"]
      Targets:
        - Arn: !GetAtt TriggerSilverToGoldLambda.Arn
          Id: TriggerLambdaTarget

  PermissionForEventsToInvokeTriggerLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TriggerSilverToGoldLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt BronzeToSilverSucceededRule.Arn

Outputs:
  GlueBronzeJob:
    Value: sylvester_bronze_to_silver
  GlueSilverJob:
    Value: sylvester_silver_to_gold
  IngestionLambda:
    Value: sylvester_ingestion_lambda
  TriggerLambda:
    Value: sylvester_trigger_silver_to_gold