AWSTemplateFormatVersion: '2010-09-09'
Description: "Base infra: IAM roles, buckets, Glue database"

Parameters:
  ArtifactsBucketName:
    Type: String
    Default: !Sub "sylvester-artifacts-${AWS::AccountId}-${AWS::Region}"
  DatalakeBucketName:
    Type: String
    Default: !Sub "sylvester-datalake-${AWS::AccountId}-${AWS::Region}"
  GlueServiceRoleName:
    Type: String
    Default: "SylvesterGlueServiceRole"
  LambdaExecutionRoleName:
    Type: String
    Default: "SylvesterLambdaExecutionRole"

Resources:

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactsBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DatalakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DatalakeBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref GlueServiceRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueAdditionalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${DatalakeBucketName}"
                  - !Sub "arn:aws:s3:::${DatalakeBucketName}/*"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
      Policies:
        - PolicyName: LambdaAdditionalPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactsBucketName}"
                  - !Sub "arn:aws:s3:::${ArtifactsBucketName}/*"
                  - !Sub "arn:aws:s3:::${DatalakeBucketName}"
                  - !Sub "arn:aws:s3:::${DatalakeBucketName}/*"

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: sylvester_glue_database

Outputs:
  ArtifactsBucketOut:
    Value: !Ref ArtifactsBucketName

  DatalakeBucketOut:
    Value: !Ref DatalakeBucketName

  GlueServiceRoleNameOut:
    Value: !Ref GlueServiceRoleName

  LambdaExecutionRoleArnOut:
    Value: !GetAtt LambdaExecutionRole.Arn